### ISSUE TITLE
リロードで言語設定が英語に戻ってしまう

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/ndmf#102]
English (United States)から日本語等に変更した後、スクリプトのリロードや再起動が入ると再びEnglish (United States)に戻ってしまいます。

**Comment by anatawa12** [comment]
Duplicate of #97?

**Comment by Sayamame-beans** [comment]
Maybe? Actually I haven't understand what's going on...

**Comment by anatawa12** [comment]
あっこれは違うわ
