### ISSUE TITLE
Object replacements record and track API

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/ndmf#118]
[context](https://misskey.niri.la/notes/9o5i9umvhm)

非破壊なツールではオブジェクトが複製されて新しいものに置き換えられることがあり、この置き換えは後に動くツールが置き換えられる前のオブジェクトを参照していた場合、設定を事実上破壊します。
主にマテリアルでその傾向が強くみられ、マテリアルを置き換えるツールは LLC や TTT など一定数存在し、それらは AAO の MargeSMR のスロットをマージを無効化や、TTT AtlasTexture などの、マテリアルを直接参照した設定を無効化や事実上動作不可にさせる可能性が存在します。

実際にはシリアライズオブジェクトを通して、すべてのコンポーネントを走査し置き換えに行くことで回避されていますが、この処理はあまり軽くはなく、それでいて その置き換えを拒否する手段も工夫しない限り無いため、この処理をあまり推奨したくはないので、
#91 でのオブジェクトの記録の仕組みと合わせて、置き換えを調べるためのAPIが欲しい。

**Comment by bdunderscore** [comment]
オブジェクト置き換えに関しては、置き換え先が複数ある場合が想定されます。例えば、TTTを例にすると、同じマテリアルとメッシュが複数のオブジェクトで使いまわされ、そのどちらもSimpleDecalを使っているが、設定値が違う場合はどうしてもメッシュかマテリアルをふたつに複製することになります。

そのため、新オブジェクトから旧オブジェクトをクエリーすることはできたとしても、逆は難しいです。新→旧クエリーで十分なら実装できそうですが、ユースケース的に十分でしょうか？

**Comment by bdunderscore** [comment]
ちなみに、現状でも`ObjectRegistry.GetReference(old) == ObjectRegistry.GetReference(new)`で判定できます。

**Comment by ReinaS-64892** [comment]
TTTの内部的な置き換え追跡は置き換え先が複数になるケースは追跡できないものとして無効化して 旧 → 新 のクエリーを使用しています。
TTT では置き換え先が分岐するケースが安定した機能の中には存在しないためこれで問題ないのですが...ほかツールとも合わせて分岐するケースを想定するとなると、新 → 旧 のクエリーだけでも何とかはなると思いますが、旧 → 分岐した最新のものすべて もあるとユースケース的にはとてもありがたいです！

**Comment by ReinaS-64892** [comment]
さっき見つけたのだけど...これとっくに解決していますね、クローズ権限持ってるようなので閉じておきますね！
