### ISSUE TITLE
NDMFプラグインが自身で追加するParamatersやMenuを申告できるようにしたい

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/ndmf#136]
Modular Avatar等にあるようなParametersやMenuなどを選択する便利なUIがNDMFプラグイン由来のそれを認識できないのは不便

- プラグイン自身が生成するものの自己申告ができる
- 申告された物が共通のインターフェースで取得できる

が満たされると嬉しい

参考までに自身のプラグインのために独自実装した物はこんな感じ
https://github.com/Narazaka/AvatarParametersDriver/commit/b011dbed8aaab0ea17f4863b41177ea46f25532e

**Comment by bdunderscore** [comment]
Menuのほうはかなり複雑になると予想しているため後回しにしますが、VRCParametersの申告は要検討

**Comment by Narazaka** [comment]
> Menuのほうはかなり複雑になる

わかる

**Comment by bdunderscore** [comment]
NDMFの思想的なんだけど、「どうしても共通化しないといけない」ところに限定させたいと考えています（そうでないとMAとNDMFの境界線がわからなくなる）

そのため、MA側のほうに実装したほうがいい気がしますが、いかが思いますか？

**Comment by Narazaka** [comment]
良さそうな気もします。NDMFツールでもそのへんはMAコンポーネントくっつける法がラクだし、必要ないのにMAいれるってことも起こりにくそう。

**Comment by Sayamame-beans** [comment]
MAに依存していないNDMFツールがExpression parameterなどを生成する可能性があり(例: [lilycalInventory](https://github.com/lilxyzw/lilycalinventory))、ツールやユーザーがパラメーター使用量を知るためにMAを経由する必要があるのは少々不自然に思います。
従って、この関連のAPIはNDMF側で持った方が良いのかなと感じています。

(なお、現在のlilycalInventory(開発版)では、親メニューにMA製のものを指定したいニーズに答えるためにMA Menu Itemをセット出来るように変更が入ったり、パラメーター使用量をプレビューする際にMA Parametersも確認するような機能が入ったりといった状態になっています。)

Related:
> NDMFに
> - パッケージ名（表示名）
> - メモリ消費元のコンポーネントまたはアセット・オブジェクト
> - メモリ消費数
> - グラフ上の色（色が同じ・似ているものがある場合は隣接しないようにするか適当な色にフォールバック）
> 
> を渡してよしなにできるようになると良さそう……？:blobcat_tabun_thinking:
> https://misskey.niri.la/notes/9qoohq9ri2

**Comment by Sayamame-beans** [comment]
このissueはパラメーターに加えてメニューについても要望しているようなので、パラメーターだけではclose出来ない気がします
(それか、別issueとして生やすか…?)
