### ISSUE TITLE
hierarchyに複数Sceneを配置し、かつSceneをUnloadしたときにBuildに失敗する

### ISSUE THREAD

**Issue by kakuchrome** [bdunderscore/ndmf#151]
アバターを同一のプロジェクトで管理するために、複数のSceneをヒエラルキーに配置した状態で、
編集中のScene以外をUnloadした状態で、Scene内あるアバターのBuildできない
（一番目のSceneのrere_arxのみ該当のエラーが発生する、別のScene移動した状態で同じく発生する）

VRCSDKのCallbackより一つ前のログがndmf関連のためこっちに投稿しました。

##回避方法
単一Sceneで編集するか、もしくはhierarchyに配置したSceneを全部Loadにした状態で回避可能

![image](https://github.com/bdunderscore/ndmf/assets/73450989/481fa7b2-d4e8-44fa-a435-f628006d6827)

[logfile.txt](https://github.com/bdunderscore/ndmf/files/14155802/logfile.txt)

**Comment by kakuchrome** [comment]
該当のエラーが発生するアバターがAAO Merged Skinned Meshのコンポーネントがありました、
（エラーが発生してないものはない）、
AAO Merged Skinned MeshのObjectをEditor Onlyの状態で試したらBuild可能の状態になったため、ndmf関連ではなさそうなので、いったんクローズします。

**Comment by anatawa12** [comment]
ログを確認させていただきましたがおそらくNDMFのバグですね。NDMFプラグインがが警告を出す場合に発生する模様ですね。該当のAAO Merge Skinned Meshがあると警告等が発生していたのだと考えられます。

**Comment by kakuchrome** [comment]
[logfile_succes.1.txt](https://github.com/bdunderscore/ndmf/files/14161903/logfile_succes.1.txt)
確認ありがとうございます。
こちらsceneを全ロードしたときにAAO Merge Skinned Meshコンポーネントありのアバターでアップロードできる状態のログです
一応prefabの整合性とるために、該当AAO Merge Skinned Meshのマージ対象元のAnimationを含めてる状態での構成の関係上でのNDMFのError Reportを無視していますが、この構成で悪さしてるですかね。

```
失敗時
ArgumentException: The scene is not loaded.
```
```
成功時
Build Framework: Saved assets in 1331ms
```

**Comment by anatawa12** [comment]
> Error Reportを無視しています

Error Reportを無視しているのが発生要件ですが、NDMFのバグであることには変わりないと思います。
