### ISSUE TITLE
エラーレポートの言語指定がregionタグの有無で増えてしまう

### ISSUE THREAD

**Issue by Azukimochi** [bdunderscore/ndmf#157]
現在のローカライゼーションでは言語タグの定義がなされておらず、ツールによって国タグ(region)が曖昧なため、"en"、"en-US"、"en-UK"などのゆらぎで言語選択メニューが増えてしまうので、国タグを削除しまとめるほうが見栄えがいいかもしれないです。
”日本語”, ”日本語(日本)" -> "日本語"

ツール間で統一も手間ですし、今後ゆらぎも増えるかもしれないので
(AAOでは次回1.7.0～ en-USにするそうです)

![image](https://github.com/bdunderscore/ndmf/assets/103747350/9f724e62-9e46-4ba6-8113-29b4033143af)

**Comment by bdunderscore** [comment]
`zh-*` を扱う場合は必須になるわけだし、国タグは考慮する予定です。とはいえ、あなたわさんの言う通り、指定がない場合は指定のあるタグすべてに充てるべきかなと考えています。
