### ISSUE TITLE
"The type or namespace name 'ScriptableSingleton<>' could not be found" error on build

### ISSUE THREAD

**Issue by enitimeago** [bdunderscore/ndmf#166]
Upon debugging why a friend's avatar was not building with MA 1.8.4 and NDMF 1.3.2 in Unity 2022, I noticed in their logs:

    Packages\nadena.dev.ndmf\Runtime\NonPersistentConfig.cs(6,42): error CS0246: The type or namespace name 'ScriptableSingleton<>' could not be found (are you missing a using directive or an assembly reference?)

The friend was able to build their avatar once I requested them to downgrade NDMF to 1.3.1.

Inspecting https://github.com/bdunderscore/ndmf/commit/2896716d1240f6fc5c3534171dd97b5472565c0c, could the source of the issue be that `NonPersistentConfig` was moved from an editor assembly to a runtime assembly, since ScriptableSingleton is a class under UnityEditor?

Log filtered to errors:

![スクリーンショット 2024-02-12 220624](https://github.com/bdunderscore/ndmf/assets/129673786/49446193-eafb-4488-ab66-b7527867837e)

**Comment by bdunderscore** [comment]
Thanks for the report, this was indeed the problem. I'll have to build some additional CI steps to catch this issue...
