### ISSUE TITLE
Error Reportウィンドウの名前を変えて欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/ndmf#173]
Error Reportという名前でありながら、warningやinfoも表示されるのは一般ユーザーにとって直感的ではありません。
また、Errorという単語があるだけで恐怖を感じたり、warning等ではなくerrorである(=直さなければならない)と認識してしまうような例もあるようでした。
そのため、Error Report、及びNDMF Error Reportの名称変更を提案します。

私からの提案は「NDMFコンソール」(NDMF Console)です。
これは、Untiyでerrorやwarning、infoが表示されるコンソール(Console)と名前を合わせる意図もあります。

**Comment by mimyquality** [comment]
参考：
infoしか無くても、このように大きく「エラー表示」と表示されます。
![image](https://github.com/bdunderscore/ndmf/assets/86596687/3286e600-4ecc-4c05-9e0a-1da7497585a1)

**Comment by anatawa12** [comment]
menu bar? https://tauri.app/v1/guides/features/menu/
