### ISSUE TITLE
ローカライズで"zh-Hant"のみを追加しても"zh-Hans”が追加され訳文がフォールバックされる

### ISSUE THREAD

**Issue by Azukimochi** [bdunderscore/ndmf#181]
NDMF 1.3.7

"zh-Hans"を追加した場合は中文(簡体)が追加され、正常ですが
"zh-Hant"を追加した場合は中文(簡体)と中文(繁体)が表示され、中文(繁体)のローカライズが中文(簡体)にも表示される

中国語の言語事情に詳しくはありませんが、これは動作としてよろしくないと判断したのでIssueとして提出させていただきました。

言語タグはこちらを参照しました
https://github.com/bdunderscore/ndmf/blob/31f538f285d365ba790c16b28ba0d4de53940870/Editor/UI/Localization/language_names.json

### "zh-Hans"を追加した場合
![image](https://github.com/bdunderscore/ndmf/assets/103747350/15b3eab6-3d97-48d8-8fd8-34b653f4ea2c)
![image](https://github.com/bdunderscore/ndmf/assets/103747350/1dbd2cfc-3bc2-48f4-b571-99e8d79c2445)
  
  
### "zh-Hant"を追加した場合
![image](https://github.com/bdunderscore/ndmf/assets/103747350/81c20e40-3d2e-4368-9b31-695e02cccd94)
![image](https://github.com/bdunderscore/ndmf/assets/103747350/297f479b-06fc-4048-9346-69af4d4c51aa)
![image](https://github.com/bdunderscore/ndmf/assets/103747350/52c29017-d8dc-44a5-82a6-95aee69c4fb6)

**Comment by bdunderscore** [comment]
Modular Avatarに`zh-hans`の翻訳が元々入っているため、言語リストに追加されます。`zh-hans`を選択した状態で`zh-hans`の翻訳がない場合は、フォールバックとして`zh-*`からデフォルト言語（この場合`en-US`）で検索します。

`zh-*`でこの挙動が適切かは判断しかねますので、バグとして扱う前に該当言語の翻訳者に相談してほしいところです。

**Comment by Azukimochi** [comment]
翻訳者の方に意見を求めてみたところ、翻訳者（繁体字話者）の方と、その方の知り合いの簡体字話者の方の意見としては`zh-hant`が`zh-hans`にフォールバックされることは問題ないそうです。

あくまで少数意見ではありますが話者視点で問題ないとの意見をいただいたので、勝手ながらこのIssueはクローズさせていただきます🙏
先にユーザー視点からの意見を求めるべきでした。お手数おかけしました🙇‍♂
