### ISSUE TITLE
ContextHolderを型だけpublicにしてほしい

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/ndmf#213]
[AAO](https://vpm.anatawa12.com/avatar-optimizer/)では過最適化や逆に最適化しないことを防ぐためにアバターについているすべてのコンポーネントについて登録を行っています。
ContextHolderも処理中に存在するためContextHolderも登録する必要があるのですが、public classになっていないためReflectionを使用する必要があります。
中身はprivate / internalのままで問題ないのでContextHolderをpublic classにしてほしいです

**Comment by bdunderscore** [comment]
Public classにしてしまうと今後削除できなくなるし、AddComponentまだきてしまうので避けたいところです。

Abstract baseや interfaceの作成を検討します
