### ISSUE TITLE
ErrorReport にて選択ボタンを作成できないときは代わりにラベルを表示してほしい

### ISSUE THREAD

**Issue by whiteflare** [bdunderscore/ndmf#223]
アバターのビルドを動かして ErrorReport を表示した場合と、再生ボタンで ErrorReport を表示した場合とで、選択ボタンの有無が異なります。

アバタービルド時
![image](https://github.com/bdunderscore/ndmf/assets/44968974/7964c467-b28f-4aca-9e65-1e7673f31aae)

再生ボタン時
![image](https://github.com/bdunderscore/ndmf/assets/44968974/d622846a-6481-46de-acfc-5331b5238e8c)

原因は、再生ボタン時には一部オブジェクトが Destroy されてしまうことにより ObjectSelector を作成できないためです。

https://github.com/bdunderscore/ndmf/blob/5617be4a9957c635e7fde444368ab18a6f7538ef/Editor/ErrorReporting/UI/SimpleErrorUI.cs#L93-L96

ObjectSelector を作成できなかった場合には、どのオブジェクトが原因でエラーが発生したかの情報が失われることになります。
そのため上の処理において `ObjectSelector.TryCreate` が false の場合にはラベルを表示して、情報が失われないようにしたいです。

**Comment by bdunderscore** [comment]
マージ済み
