### ISSUE TITLE
何か置き換え追跡用の仕組みが必要です！

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/ndmf#276]
マテリアルの置き換えの追跡などの、オブジェクトレジストリーに書き込み、それを読み取ることで実現できていた、置き換え追跡が、NDMFプレビューでは行えない問題があります。
何かしらの手段で行えると嬉しいです！

**Comment by bdunderscore** [comment]
予定としては、

```
public sealed class PreviewContext {
    public IObjectRegistry ObjectRegistry { get; }
}
```

みたいなのを`Instantiate`と`Refresh`に渡すかなと考えています。（ObjectRegistry自体ではなく、同じAPIの別実装になる予定です）
