### ISSUE TITLE
プレビューのオンオフをできる部分の表示名を任意の物に変更したい

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/ndmf#301]
TTT はパス一つ一つにレンダラーフィルターが付いているわけではなく、中間のパスにレンダラーフィルターをつける実装なため、表示名がパスの名前だと具体的にどのフェーズがオンオフされるのか、(中身をすべて知っている私はわかりますが...)非常に分かりずらくなってしまうのでそれを何とかしたいです！
![image](https://github.com/user-attachments/assets/8ebb313c-8d97-4f3c-8384-3855f464f46d)

**Comment by bdunderscore** [comment]
ふむ・・・名前だけでなく、内容を全部変更できるようにしないといけないっぽいですね
