### ISSUE TITLE
[PreviewSystem] 前のノードが Instantiate された後に同じレンダラーを参照する Node が Instantiate されていない...?

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/ndmf#322]
私の実装が悪い可能性もあるので、悪いところがあれば教えてほしいです！(多少はいじってみたのですが何もわからなかったのでこのissueを書いています。)

まず状況として、レンダラー Cube に MultiLayerImageCanvas と SimpleDecal が付いている状態で、
- Cube 
  - MLIC
  - SD

このような状態になっています。
この状態で Cube のテクスチャを変更する MLIC の状態を変化させたらノードが更新され、その次 Cube に作用する SD も引きずられてノードが更新されると思うのですが...全く更新されず SD の影響が消え去ってしまいます。
[NA-Test.zip](https://github.com/user-attachments/files/16568526/NA-Test.zip)

環境

- NDMF main 7bf328f66cd44baf8499bccabe66ce9cb8eca379
- TTT dev https://github.com/ReinaS-64892/TexTransTool/commit/eed90786737a4e7ed2af540e7232a7e29c0a7321

**Comment by ReinaS-64892** [comment]
[ctx](https://x.com/aou_vrc/status/1831995961025126529)
どうやら refreshを実装すると後のノードも正しく動くそうです、謎ですが....

**Comment by bdunderscore** [comment]
@ReinaS-64892 最新のバージョンでも再現できますか？

**Comment by ReinaS-64892** [comment]
ffeb256fc9fcdb86a843046fa65f247dfb0c8f5d でも再現します！

**Comment by anatawa12** [comment]
270050c2e024e117ed73dc4af4e8a3a29719a9f9 でも発生してる気がする (AAO Remove Mesh by BlendShapeとin Boxの間でこれっぽい動作があった)

**Comment by bdunderscore** [comment]
![image](https://github.com/user-attachments/assets/52a622fd-ee31-4881-87b3-1e837960c886)

この再現に関しては、CubeとQuadが独立したRenderGroupなので、最初のDomainFilterでCubeが更新されたら、二つ目のDomainFilterでCubeのみが更新されます。両方更新したい場合は、二つとも入っているGroupにしてください。

**Comment by bdunderscore** [comment]
この辺がいろいろとわかりづらいのでデバッグ機能の追加を検討します。
