### ISSUE TITLE
ModularAvatarがインストールされてるかに関わらずNDMFのManualBakeを表示してほしい

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/ndmf#33]
AAOのドキュメントで紹介する場合にMAが入っているかどうかで場所が変わる説明するのは少し面倒なため常に表示してほしいです

**Comment by bdunderscore** [comment]
うーん、コンテキストメニューに出すと邪魔になりそうなので、Toolsのところだけに表示しようかなと考えています

**Comment by anatawa12** [comment]
うーん...コンテクストにも欲しいです
