### ISSUE TITLE
Support for VRChat World SDK?

### ISSUE THREAD

**Issue by KisaragiEffective** [bdunderscore/ndmf#332]
需要があるらしい:
* https://misskey.niri.la/notes/9x2lkoifjv
* https://misskey.niri.la/notes/9x2m91g5op
* https://misskey.niri.la/notes/9x2n0fqs7m

[Any Time](https://github.com/dotnet/csharplang?tab=readme-ov-file#milestones) ならその旨を書いておいてくれると嬉しいです

**Comment by bdunderscore** [comment]
アーキテクチャ的にはアバターとワールドが違いすぎるのでNDMFをベースにする必要性をあまり感じない気がします。。。

具体案があったら聞きます。

**Comment by bdunderscore** [comment]
現状、対応したとしてもまったくの別物にならざるを得ないと考えているためクローズします。
