### ISSUE TITLE
[PreviewSystem] 前のレンダラーフィルターが行った置き換えの追跡に失敗する

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/ndmf#349]
どこが原因かはあまり追えていないですが... ActiveRegistry に前の置き換えの記録が入ってい状態になっています。

NDMF プレビュー
![image](https://github.com/user-attachments/assets/d82b3d1a-0518-48a7-90bb-fcd9a630cdae)

ビルド
![image](https://github.com/user-attachments/assets/3b11971d-65ed-4c6e-958b-c77802a7bb88)

再現用プレハブ [RQT.zip](https://github.com/user-attachments/files/16735872/RQT.zip)
Environment
- NDMF 2dcca7626a7342896930e1fef549b5121df89e9b
- https://github.com/ReinaS-64892/TexTransTool/commit/39aea7ac488d2bc7d9154ed715e378bdb0921e4e

**Comment by bdunderscore** [comment]
![image](https://github.com/user-attachments/assets/70e51d47-e988-43c3-8a48-d820a7d2a963)

TTTのほうでMaterialを上書きしてる（`sharedMaterials`ではなく`materials`でアクセルしてる？）っぽい？

**Comment by bdunderscore** [comment]
（デバッガーの影響かも）
