### ISSUE TITLE
[Preview System] プレビューの対象となっているレンダラー以外の可視設定の変更イベントを拾ってしまっている

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/ndmf#352]
恐らく...主にこの部分

https://github.com/bdunderscore/ndmf/blob/6fa2554072efa681859410cda98783176d18d9ed/Editor/PreviewSystem/Rendering/VisibilityMonitor.cs#L15-L20

これによって、TTT AtlasTexture 内で一時的な Renderer と GameObject が生成されたときに可視設定の変更が発火されて無限ループ起こしたり、手動で全く無関係な GameObject の可視設定をいじった時に不必要なリフレッシュがされるようになってしまっています！

**Comment by bdunderscore** [comment]
#355 で修正
