### ISSUE TITLE
[PreviewSystem] Always enable Selection Outline of the Renderer

### ISSUE THREAD

**Issue by Tliks** [bdunderscore/ndmf#357]
Rendererを選択した際にシーン上に表示されるSelection Outlineですが、NDMF Previewが有効なRendererに対してはこのSelection Outlineが外れることがあります。Hierarchyではなくシーン上から選択した場合や有効/無効を切り替えたタイミングなどで外れています。

Selection OutlineはRendererの選択状態や輪郭線の確認に重宝しているので、可能かは分かりませんが常に表示されるように変更されると助かります。

**Comment by bdunderscore** [comment]
バグですが、再現手順ありますか？

**Comment by Tliks** [comment]
一部再現性低いですが以下の手順で再現できました。

- Scale AdjusterをHips等につけて対象のRendererをシーン上から選択(単一のRendererが対象な場合は外れる可能性は高そう)
- [このコード](https://github.com/Tliks/SceneMeshUtils/blob/223e152384d81f72fb4da4da829b72e5758933f0/Editor/EditModePreview/RemoveMeshFromScenePreview.cs)を付与したRendererをシーン上から選択したり、コンポーネントの値を変更してInstanciateが呼ばれたタイミング、previewがtoggleされたタイミングでそれぞれOutlineが外れます。
- AAO Remove Meshも似た実装だと思いますが、Reinaさんに確認してもらった感じ同様にシーン上の選択、コンポーネントの値変更、PreviewのToggle等でoutlineは外れるようです

**Comment by bdunderscore** [comment]
主な原因が二つありました

1. PreviewPipelineがInvalidateされるたびに、プロクシーオブジェクトを入れ替える処理が入りますが、この副作用でオブジェクト選択の状態が破棄される
2. 毎フレームPreviewPipelineがInvalidateされてた (#372で修正)

1 のほうはリリース後の修正としまして、2を修正すればたぶんあまり当たらないはず。

**Comment by bdunderscore** [comment]
なおこのイッシューは1の修正が完了するまで残します。

**Comment by Tliks** [comment]
シーン上からの選択でSelection Outlineが外れなくなったのは確認しました、ありがとうございます。
一方でコンポーネントの値を変更しInstanciateが呼ばれたタイミングで2回に一回outlineが外れたり、previewをtoggleしても外れる動作は引き続きあるようです。必要であれば独立issueを立てます
