### ISSUE TITLE
ErrorReportが作成されたことをテストするための仕組みがほしい

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/ndmf#359]
ツールのテスト用にErrorReportの中身にアクセスしてアサートする方法がほしいです

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/modular-avatar/blob/c6e863d4091e4ab4d45d2a085297cf7f24c71a1d/UnitTests~/ReplaceObject/ReplaceObjectTests.cs#L105-L110

既存です。
