### ISSUE TITLE
[PreviewSystem] duplicated refreshes are triggered by selection from scene.

### ISSUE THREAD

**Issue by Tliks** [bdunderscore/ndmf#376]
起動時やPlayModeを終了し全フィルターのInstantiateが終了したタイミングで、シーンからメッシュを選択するとそのメッシュを対象とするフィルターの全TargetGroupが再度Instantiateを呼びます。
Hierarchyから選択した場合は呼ばれません。

TTT AtlasTexture等で確認しました。

同一フィルターの他TragetGroupのInstantiateが呼ばれるという点は #375 に関係していると思います。仕様だったらすみません。

NDMF: 1.5.0-rc.4

**Comment by bdunderscore** [comment]
Unityの仕様上、変更があるかどうか判断しかねる場合がかなりあります。そのため、適当なタイミングでComputeContextがInvalidateされることがしょっちゅうあります。

このバグに関しては、`ObjectChangeKind.ChangeScene`という、「何が変わったかは分からないけどなんか変わりました！」のお知らせがUnity のネーティブ側から来たのが原因だと思われます。対処が困難なので、重くなっているプレビュープラグインのほうで適切に `ComputeContext.Observe` の変更なし判定を設定することをお勧めします。
