### ISSUE TITLE
シーンを開き直すとプレビューが表示されなくなる

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/ndmf#396]
シーンを開き直すとプレビューが表示されなくなります。

再現手順です。
1. Unity を起動する
2. [再現シーン](https://github.com/user-attachments/files/17004638/reopen_scene.zip) をインポートする
3. Test シーンをダブルクリックして開く (プレビューが表示される)
4. Test シーンをダブルクリックして開き直す (プレビューが表示されない)

eef1d86 から発生しているようです。(MA は最新 main で確認)

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/ndmf/pull/397 と同じ問題だったっぽい
