### ISSUE TITLE
Duplicate 'ExportsPlugin' attribute` error when declaring multiple plugins

### ISSUE THREAD

**Issue by hai-vr** [bdunderscore/ndmf#40]
Having multiple ExportsPlugin for targeting different classes extending Plugin seems to trigger a compilation error:
- `Assets\_Hai_IKG_Misty\IKGAsCode\YourScript.cs(7,12): error CS0579: Duplicate 'ExportsPlugin' attribute`

**Comment by bdunderscore** [comment]
Fixed in #45
