### ISSUE TITLE
[ObjectRegistry] Unity における同一オブジェクトを正しく同一と評価できておらず、追跡に失敗する

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/ndmf#415]
C# 側で違うオブジェクトになる状況が発生するようです。なので以前のように Instance ID で判定しないと正しく置き換えが追跡できず、新しい ObjectReference が生成されてしまうようです。

https://github.com/bdunderscore/ndmf/blob/ffeb256fc9fcdb86a843046fa65f247dfb0c8f5d/Editor/API/ObjectRegistry.cs#L151

![image](https://github.com/user-attachments/assets/54e6313d-7de6-426e-94e2-09eaee4206f0)

以前はこのようなコードで、 GetHashCode ( 恐らく中身は InstanceID ) で判別していたから正しく動作していたようですね！
https://github.com/bdunderscore/ndmf/blob/11ac19a07c1910a4586292151a752d6eeea83bdd/Editor/API/ObjectRegistry.cs#L74

**Comment by ReinaS-64892** [comment]
前言一部撤回 これ v1.4.1 の方でも発生しているようですし、調べたところ  RuntimeHelpers.GetHashCode() は C# の本当の HashCode を返すようなので Unity としては同一であったとしても外れます！！！

恐らく今まで LLC4MA 動作後に TTT AtlasTexture が動作で来ていたのは C# としては偶然同一オブジェクトだったからである可能性が高いです...

VRCFury との併用で TTT が置き換えの追跡を見失う原因はほぼこれなんじゃないかとも思います。

RuntimeHelpers.GetHashCode() を使用せずに obj.GetHashCode() （Unity の InstanseID）を用いた場合 LLC4MA + VRCFury + TTT AtlasTexture の状態でも正しく動作できるので....

**Comment by bdunderscore** [comment]
GetHashCodeを使っている理由ですが、GetInstanceIDを使うとオブジェクト破壊後例外を吐いていろいろとDictionaryが爆発しますね・・・

RuntimeHelpers.GetHashCodeが異なるということは、同じUnityオブジェクトに対して複数のC# objectが存在するということですか？

**Comment by ReinaS-64892** [comment]
そうです、InstanceID は同じだけど m_CachedPtr は違う C# Object が存在することがありました。

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/modular-avatar/pull/1211
https://github.com/bdunderscore/ndmf/pull/416

**Comment by bdunderscore** [comment]
上記二つのPRで直りますか？

**Comment by ReinaS-64892** [comment]
よさそう！治ってる！
![スクリーンショット 2024-09-26 125800](https://github.com/user-attachments/assets/ca237e09-a7be-4fbd-bad2-088e90b63fff)
