### ISSUE TITLE
[PreviewSystem] Always enable Selection Outline of the Renderer

### ISSUE THREAD

**Issue by Tliks** [bdunderscore/ndmf#446]
related to #357 
上記issueにてシーン上からRendererを選択された際のOutlineは保持されるようになりましたが、Instanciateが走るタイミング等で引き続きOutlineが外れます。

具体的な操作は以下の通りです。

Rendererに対してShape Changerをアタッチした環境下で、
- コンポーネント(Shape Changer)の追加、削除
- Rendererがついたオブジェクトのアクティブの切り替え

でOutlineが消えます。また、
-  Shape ChangerへのBlendShapeの追加、削除 

でOutlineが消えたり復活したりを繰り返します。恐らく同様の原因でNDMF Previewの対象となっているSkinnedMeshRendererの
- BlendShapeのスライダーの操作

でOutlineは点滅します

NDMF: 1.5.4で確認しました。

**Comment by bdunderscore** [comment]
`SceneView.s_SelectionCacheDirty` をセットする必要があるようです
