### ISSUE TITLE
[ChangeNotifier.cs] AssetPostprocessor causes memory leak, crash

### ISSUE THREAD

**Issue by GapVR** [bdunderscore/ndmf#489]
AssetPostprocessor causes 100% memory usage and crashes Unity.

Problem solved after removing lines 51-59 in ChangeNotifier.cs.

---

Could not allocate memory: System out of memory!
Trying to allocate: 22369620B with 16 alignment. MemoryLabel: Texture
Allocation happened at: Line:72 in C:\build\output\unity\unity\Runtime\Core\Containers\Vector.h

**Comment by bdunderscore** [comment]
This should be fixed in https://github.com/bdunderscore/ndmf/commit/b7053ca644572b051fa9a657e6e3c640e7ce8673 and will be in the next release

**Comment by bdunderscore** [comment]
Released in 1.6.2
