### ISSUE TITLE
feat: Non-VRChat Avatars support

### ISSUE THREAD

**Issue by kaikoga** [bdunderscore/ndmf#49]
### Discussed in https://github.com/bdunderscore/ndmf/discussions/39

Remove VRCSDK dependencies from ndmf to support non-VRChat avatars.

## Required Tasks

- [x] Add Version Define `NDMF_VRCSDK3_AVATARS` against "com.vrchat.avatars"
- [x] `#if NDMF_VRCSDK3_AVATARS` VRCSDK component references and public API hooks
- [x] Cross platform find Avatar root 

## Optional Tasks (separate issue?)

- Obsolete duplicate AvatarRoot APIs
- CI and unit tests without VRCSDK

**Comment by bdunderscore** [comment]
CI should now be attempting to run unit tests without VRCSDK - since the unit tests don't work quite yet, I've suppressed the failures (these will show up as "neutral" results)

**Comment by kaikoga** [comment]
#68
#69

**Comment by kaikoga** [comment]
I think remaining tasks go to separate issue.
