### ISSUE TITLE
Do not Suppress ApplyOnPlay even when using AV3Emulator

### ISSUE THREAD

**Issue by sakuraimikoto33** [bdunderscore/ndmf#64]
Do not Suppress ApplyOnPlay even when using AV3Emulator
https://github.com/bdunderscore/ndmf/issues/16
https://github.com/bdunderscore/ndmf/issues/23

Av3Emulator is a Curated package.
Unlike GestureManager, AV3Emulator has a clear advantage of being able to control RadialMenu from a list and checking all states without page/tab transitions.
If you continue to restrict it, either run it with a warning or optionally change it to allow it to run even if AV3Emulator is present.
Please do not suppress.

**Comment by anatawa12** [comment]
You should use Run Preprocess Avatar Hook in Av3Emurator instead.
To not conflict with Run Preprocess Avatar Hook, Apply on Play is disabled if Av3Emu is active.
