### ISSUE TITLE
NDMFとFaceEmoでpackage.jsonやEditorとGUIDがかぶっています

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/ndmf#79]
恐らくテンプレートリポジトリそのままの物を使っているからかと？
![image](https://github.com/suzuryg/face-emo/assets/1712548/8ad184c6-5d04-4e95-8eb6-6172e2aeaf56)

**Comment by Narazaka** [comment]
https://github.com/suzuryg/face-emo/issues/76

**Comment by bdunderscore** [comment]
🙄 🙄 🙄
