### ISSUE TITLE
[ErrorReport] [FEATURE] interface to provide context object

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/ndmf#96]
I want to pass some object that holds single (or multiple) context object to InlineError

**Comment by bdunderscore** [comment]
Would this be satisfied by #95 ?

**Comment by anatawa12** [comment]
I want to pass objects that isn't a collection but provides context objects so I want NDMF to have some both iterating over IEnumerable recursively and some interface only for providing context object
